name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk build-essential libssl-dev libffi-dev python3-dev
        sudo apt install -y autotools-dev autoconf automake libtool pkg-config
    
    - name: Install buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
    
    - name: Create minimal buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Konum Takip
        package.name = locationtracker
        package.domain = com.example.locationtracker
        source.dir = .
        version = 1.0
        requirements = python3,kivy
        orientation = portrait
        fullscreen = 0
        android.api = 31
        android.minapi = 21
        android.sdk = 31
        android.ndk = 25b
        android.private_storage = True
        android.permissions = INTERNET,ACCESS_NETWORK_STATE,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION,WAKE_LOCK
        android.archs = arm64-v8a
        [buildozer]
        log_level = 2
        EOF
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
